package panelfx.poker.domain.model;
public enum PokerVariant {

    TEXAS_HOLDEM,
    OMAHA_HOLDEM,
	PINEAPPLE_HOLDEM,
	CRAZY_PINEAPPLE_HOLDEM,
    FIVE_CARD_STUD,
    SEVEN_CARD_STUD,
    FIVE_CARD_DRAW,
    DEUCE_TO_SEVEN_SINGLE_DRAW,
    DEUCE_TO_SEVEN_TRIPLE_DRAW,
    ANACONDA_DRAW,
	SHOTGUN_DRAW
}
